### ISSUE TITLE
Make your own list

### ISSUE THREAD

**Issue by xkvcr** [Klarala13/Yuki-contacts#4]
What's the point of “make your own list”? You could just add them from the main table, right?

**Comment by Klarala13** [comment]
Yes, that's the point.. to add them from the main table, that's why there is the add button

**Comment by xkvcr** [comment]
But they only show up on the right side?

**Comment by Klarala13** [comment]
In the project description it says it needs to be an entirely different list... "This app will have two different data lists where the user can visualize a list of contacts. These data lists should be sortable and filterable. Additionally, the user can add/edit contacts from the contact list through a form."

**Comment by xkvcr** [comment]
Okay, good to know. I have an idea of how to do it. You could use tabs and/or `react-router`, right? Do they forbid any of these?

**Comment by Klarala13** [comment]
nop

**Comment by Klarala13** [comment]
we can do it as we like

**Comment by Klarala13** [comment]
I'm working on adding them to the new list and, for now, I'm adding them but to the old one, but i'm almost there!
